name: Deploy

on:
  push:
    branches: [master]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        run: npm i
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.d42c5282-a58d-4291-b08e-d3940453ee8b}}
          heroku_app_name: "ws16inmonday" #Must be unique in Heroku
          heroku_email: "nadav6295@gmail.com"
