# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
# [to be filled]
jobs:
  test:
    runs-on: # [to be filled]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        # [rest to be filled]
  build-deploy:
    runs-on: # [to be filled]
    steps:
    # [rest to be filled]


name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        run: npm i
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{091220ca-5ba6-41be-a467-91449580f7e9}}
          heroku_app_name: "ws16inmonday" #Must be unique in Heroku
          heroku_email: "nadav6295@gmail.com"
